image: node:14.9.0

include:
  - template: Security/Secret-Detection.gitlab-ci.yml

stages:
  - build
  - test

Build system:
  stage: build
  
  script:
    - npm install

Code Linting:
    stage: test

    before_script:
        - npx install-peerdeps --dev @lnu/eslint-config

    script:
        - npx eslint
